version: "2"

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    networks:
      - plexnet
    environment:
      - OPENVPN_PROVIDER=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - WEBPROXY_ENABLED=yes
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - /docker/transmission:/data
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1002
      - TZ=Europe/London
    volumes:
      - /docker/radarr/config:/config
      - /docker/transmission/completed:/downloads
      - /share/medias/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1002
      - TZ=Europe/London
    volumes:
      - /share/medias/animes:/animes
      - /share/medias/series:/series
      - /docker/sonarr/config:/config
      - /docker/transmission/completed:/downloads
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1002
      - TZ=Europe/London
    volumes:
      - /docker/jackett/config:/config
      - /docker/jackett/downloads:/downloads
    ports:
      - "9117:9117"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - plexnet
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "8191:8191"
    restart: unless-stopped 
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1002
      - TZ=Europe/London
    volumes:
      - /docker/plex/config:/config
      - /share/medias/movies:/movies
      - /share/medias/series:/series
      - /share/medias/animes:/animes
networks:
  plexnet:
    driver: bridge
